id: I51763B50
legacy_id: P000302
ocr_import_info:
  bdrc_scan_id: W24767
  source: bdrc
  ocr_info:
    timestamp: '2020-03-10T18:58:09'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:38:13.355604+00:00'
last_modified: 2022-09-02 13:39:53.391856
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W24767
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW24767
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལམ་འབྲས་གཞུང་རྡོ་རྗེའི་ཚིག་རྐང་གི་རྣམ་འགྲེལ་བཅུ་གཅིག
  author: ས་ཆེན་ཀུན་དགའ་སྙིང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6845327000104922
  ocr_word_median_confidence_index: 0.75
quality: null
bases:
  I3852:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3852
      total_pages: 542
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3852.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6642306663374494
    legacy_id: v001
  I3854:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3854
      total_pages: 502
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I3854.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.6917657575599094
    legacy_id: v003
  I3853:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3853
      total_pages: 504
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3853.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7034285338273331
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
