id: I51763B50
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-10T19:01:22+00:00'
last_modified: '2022-06-15T15:17:39.329440+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W24767
  title: ལམ་འབྲས་གཞུང་རྡོ་རྗེའི་ཚིག་རྐང་གི་རྣམ་འགྲེལ་བཅུ་གཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7A34:
      image_group_id: I3852
      title: ''
      total_pages: 542
      order: 1
      base_file: 7A34.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
